<Workspace Version="1.3.0.875" X="0" Y="0" zoom="1" ScaleFactor="1" Name="CompasMesh.VertexPositions" Description="Return the vertex positions of the compas mesh as a list of Dynamo points." ID="cf5e380c-4ed7-4f87-a53e-85095fb8705e" Category="Compas.Datastructures.Mesh">
  <NamespaceResolutionMap>
    <ClassMap partialName="Line.By" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="f757f435-ca6c-41d9-91b0-90f475de3c67" type="PythonNodeModels.PythonNode" nickname="CompasMesh.VertexPositions" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import sys

with open('C:/Temp/compas_path.txt', 'r') as f:
    compas_path = f.readline().strip()
    iron_path = f.readline().strip()

sys.path.insert(0, iron_path)
sys.path.insert(0, iron_path + 'DLLs')
sys.path.insert(0, iron_path + 'Lib')
sys.path.insert(0, compas_path)

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import compas
from compas.datastructures.mesh import Mesh

mesh = IN[0]

key_index = mesh.key_index()

vertices = [mesh.vertex_coordinates(key) for key in mesh.vertices()]
points = [Point.ByCoordinates(x, y, z) for x, y, z in vertices]

OUT = points</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="46ee6f7f-2099-4781-97ab-20886072e252" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="CompasMesh" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5e02a146-7d50-4f6d-b84b-8fe50ce247eb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="521" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Point[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f757f435-ca6c-41d9-91b0-90f475de3c67" start_index="0" end="5e02a146-7d50-4f6d-b84b-8fe50ce247eb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="46ee6f7f-2099-4781-97ab-20886072e252" start_index="0" end="f757f435-ca6c-41d9-91b0-90f475de3c67" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>