<Workspace Version="1.3.0.875" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Compas.Pointcloud_2D" Description="Create a 2D pointcloud." ID="288d9317-cf1a-4ca1-b80c-1b0c377d15c9" Category="Compas">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="c3f3155a-9646-4995-926b-8ecd34dc169d" type="PythonNodeModels.PythonNode" nickname="Compas.Pointcloud_2D" x="250" y="0" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import sys

with open('C:/Temp/compas_path.txt', 'r') as f:
    compas_path = f.readline().strip()
    iron_path = f.readline().strip()

sys.path.insert(0, iron_path)
sys.path.insert(0, iron_path + 'DLLs')
sys.path.insert(0, iron_path + 'Lib')
sys.path.insert(0, compas_path)

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import compas
from compas.geometry import pointcloud_2d

xmin = IN[0]
xmax = IN[1]

n = IN[2]

cloud = pointcloud_2d(n, (xmin, xmax))

points = [Point.ByCoordinates(x, y, z) for x, y, z in cloud]

OUT = points</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="78555fb4-9541-4913-99f7-5f2b751c7600" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="xmin" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="67fa2a4c-938e-4913-9039-52235a3f32a8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="150" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="xmax" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="63666112-7bea-4d28-964f-913bb33fa929" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-1" y="300" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="n" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="81c6e159-6f86-4c2f-87d3-5151748b14cd" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="479" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Point[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c3f3155a-9646-4995-926b-8ecd34dc169d" start_index="0" end="81c6e159-6f86-4c2f-87d3-5151748b14cd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="78555fb4-9541-4913-99f7-5f2b751c7600" start_index="0" end="c3f3155a-9646-4995-926b-8ecd34dc169d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="67fa2a4c-938e-4913-9039-52235a3f32a8" start_index="0" end="c3f3155a-9646-4995-926b-8ecd34dc169d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="63666112-7bea-4d28-964f-913bb33fa929" start_index="0" end="c3f3155a-9646-4995-926b-8ecd34dc169d" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>