<Workspace Version="1.3.0.875" X="86.5" Y="22" zoom="1" ScaleFactor="1" Name="CompasNetwork.leaf_vertices" Description="returns the leaf vertices and indices of a compas network" ID="ded733d1-71f7-4d37-b471-92d7135d533f" Category="Compas.Datastructures.Network">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="fd0e2900-1ad0-4aa9-9c19-f884b51108c3" type="PythonNodeModels.PythonNode" nickname="CompasNetwork.leaf_vertices" x="250" y="-1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import sys

with open('C:/Temp/compas_path.txt', 'r') as f:
    compas_path = f.readline().strip()
    iron_path = f.readline().strip()

sys.path.insert(0, iron_path)
sys.path.insert(0, iron_path + 'DLLs')
sys.path.insert(0, iron_path + 'Lib')
sys.path.insert(0, compas_path)

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import compas
from compas.datastructures.network import Network

network = IN[0]

vkeys = [k for k in network.vertex if network.is_vertex_leaf(k)]
vert = [network.get_vertex_attributes(k, ['x', 'y', 'z']) for k in network.vertex if network.is_vertex_leaf(k)]
points = [Point.ByCoordinates(v[0], v[1], v[2]) for v in vert]
OUT = [points, vkeys]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9f4aafb0-8b8f-462b-92e5-9fed67ca08b1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="CompasNetwork" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="1c15f5f0-c8c8-4dde-b822-ff5b15f6923a" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="662.975525359124" y="-21.6269271857747" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Points" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="7e03741f-5eeb-46e5-8963-dafff6707c38" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="671.487762679562" y="84.0797842541474" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Indices" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="2973dbd8-0456-4348-9dc1-b8078a510406" type="PythonNodeModels.PythonNode" nickname="Python Script" x="496.753649623323" y="-22.7891134299095" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
OUT = IN[0][0]</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="52c057ce-fd05-4d6a-9d5f-f8f260c31d7f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="484.947207865716" y="77.6986492496526" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
OUT = IN[0][1]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fd0e2900-1ad0-4aa9-9c19-f884b51108c3" start_index="0" end="2973dbd8-0456-4348-9dc1-b8078a510406" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fd0e2900-1ad0-4aa9-9c19-f884b51108c3" start_index="0" end="52c057ce-fd05-4d6a-9d5f-f8f260c31d7f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9f4aafb0-8b8f-462b-92e5-9fed67ca08b1" start_index="0" end="fd0e2900-1ad0-4aa9-9c19-f884b51108c3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2973dbd8-0456-4348-9dc1-b8078a510406" start_index="0" end="1c15f5f0-c8c8-4dde-b822-ff5b15f6923a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="52c057ce-fd05-4d6a-9d5f-f8f260c31d7f" start_index="0" end="7e03741f-5eeb-46e5-8963-dafff6707c38" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>