<Workspace Version="1.3.0.875" X="0" Y="0" zoom="1" ScaleFactor="1" Name="CompasMesh.from_polyhedron" Description="Create a compas mesh from a platonic solid." ID="0f981d80-cb96-4e5d-9a19-989e05afbb56" Category="Compas.Datastructures.Mesh">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="13cefa04-0642-4627-97b4-bf2d185886e7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import sys

with open('C:/Temp/compas_path.txt', 'r') as f:
    compas_path = f.readline().strip()
    iron_path = f.readline().strip()

sys.path.insert(0, iron_path)
sys.path.insert(0, iron_path + 'DLLs')
sys.path.insert(0, iron_path + 'Lib')
sys.path.insert(0, compas_path)

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import compas
from compas.datastructures.mesh import Mesh
from compas.geometry.elements import Polyhedron
from compas.datastructures.mesh.algorithms import scale_mesh

number_of_faces = IN[0]
scale = IN[1]

if number_of_faces in (4, 6, 8, 10, 12):
	polyhedron = Polyhedron.generate(number_of_faces)
	mesh = Mesh.from_vertices_and_faces(polyhedron.vertices, polyhedron.faces)
	scale_mesh(mesh, scale)
else:
	mesh = None

OUT = mesh</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8ebd80e5-40d8-4817-b081-4c3f3d19bbe4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="48" y="1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="number of faces" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3c1f4c31-f730-4dbf-bf57-f0d2e43d273f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="50" y="61" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="scale" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="afe325ad-cbe0-4f43-aaa5-14762f02953c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="CompasMesh" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="13cefa04-0642-4627-97b4-bf2d185886e7" start_index="0" end="afe325ad-cbe0-4f43-aaa5-14762f02953c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8ebd80e5-40d8-4817-b081-4c3f3d19bbe4" start_index="0" end="13cefa04-0642-4627-97b4-bf2d185886e7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3c1f4c31-f730-4dbf-bf57-f0d2e43d273f" start_index="0" end="13cefa04-0642-4627-97b4-bf2d185886e7" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>