<Workspace Version="1.3.0.875" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Mesh.ByCompasMesh" Description="Make a dynamo mesh from a compas mesh" ID="b17ac3cb-cbcc-4282-b34a-eda1d9151d7e" Category="Compas.Datastructures.Mesh">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="9bf58218-ea12-48b2-8af5-883ec06e74ee" type="PythonNodeModels.PythonNode" nickname="MeshToVertices" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import sys

with open('C:/Temp/compas_path.txt', 'r') as f:
    compas_path = f.readline().strip()
    iron_path = f.readline().strip()

sys.path.insert(0, iron_path)
sys.path.insert(0, iron_path + 'DLLs')
sys.path.insert(0, iron_path + 'Lib')
sys.path.insert(0, compas_path)

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import compas
from compas.datastructures.mesh import Mesh

mesh = IN[0]

xyz = [mesh.vertex_coordinates(key) for key in mesh.vertices()]

points = [Point.ByCoordinates(x, y, z) for x, y, z in xyz]

OUT = points</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="0413386e-79c0-4176-8d57-fa54234bfa95" type="PythonNodeModels.PythonNode" nickname="MeshToFaces" x="251" y="83" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import sys

with open('C:/Temp/compas_path.txt', 'r') as f:
    compas_path = f.readline().strip()
    iron_path = f.readline().strip()

sys.path.insert(0, iron_path)
sys.path.insert(0, iron_path + 'DLLs')
sys.path.insert(0, iron_path + 'Lib')
sys.path.insert(0, compas_path)

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import compas
from compas.datastructures.mesh import Mesh

mesh = IN[0]

key_index = mesh.key_index()

faces = [mesh.face_vertices(fkey) for fkey in mesh.faces()]
faces = [[key_index[key] for key in face] for face in faces]
faces = [IndexGroup.ByIndices(*face) for face in faces]

OUT = faces</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0c757583-4b6a-4bca-ae15-d1f0b1c50136" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Mesh.ByPointsFaceIndices" x="410.5" y="26.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Mesh.ByPointsFaceIndices@Autodesk.DesignScript.Geometry.Point[],Autodesk.DesignScript.Geometry.IndexGroup[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2a4a6864-ae94-41be-af13-53c9327880c1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="CompasMesh" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5a8f3a02-d793-445c-82c3-f3c84f082bfe" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="730.5" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Mesh" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9bf58218-ea12-48b2-8af5-883ec06e74ee" start_index="0" end="0c757583-4b6a-4bca-ae15-d1f0b1c50136" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0413386e-79c0-4176-8d57-fa54234bfa95" start_index="0" end="0c757583-4b6a-4bca-ae15-d1f0b1c50136" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0c757583-4b6a-4bca-ae15-d1f0b1c50136" start_index="0" end="5a8f3a02-d793-445c-82c3-f3c84f082bfe" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2a4a6864-ae94-41be-af13-53c9327880c1" start_index="0" end="9bf58218-ea12-48b2-8af5-883ec06e74ee" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2a4a6864-ae94-41be-af13-53c9327880c1" start_index="0" end="0413386e-79c0-4176-8d57-fa54234bfa95" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>